<@page.board title=i18n('welcome') subtitle=i18n('welcome2')>
    <@layout.cards>
        <@layout.card emoji='bust_in_silhouette' label='Users' link='/User/list' />
        <@layout.card emoji='books' label='Entities' link='/SimpleEntity/list' />
        <@layout.card emoji='ant' label='Exceptions' link='/Exceptions/list' />
        <@layout.card emoji='closed_lock_with_key' label='Restricted' link='/RestrictedAccess/list' />
    </@>
</@>