== Freemarker Templates

=== Why Freemarker ?

During our migration to Quarkus, we tried to reimplement our Freemarker components with Qute, the template engine proposed by the Quarkus team. But it was lacking some features needed for it. As the Weblith UI components base was already well-defined and stable, the choice have been made to continue using Freemarker, using the https://quarkiverse.github.io/quarkiverse-docs/quarkiverse-freemarker/dev/index.html[Quarkiverse Freemarker extension]. Be sure to check that extension documentation to discover the Freemarker dedicated configuration properties.

TIP: Refer to the https://freemarker.apache.org/docs/index.html[Freemarker] documentation for more information about how to use this template engine.

=== Rendering templates

Do you remember the different `Result` classes Weblith was offering? That's the same case here. Simply return a `HtmlResult` to render a Freemarker template. This result must point to a template directory followed by a template name.

TIP: Giving only a template name will use the current controller's name as the template directory.

[source,java]
----
    @Get("/")
    public HtmlResult home() {
        return new HtmlResult("Main", "home") <1>
            .render("MyData","MyValue"); <2>
    }
----
<1> Will render the template `Main/home.ftlh` (located by default in your `freemarker/templates` resources).
<2> With a `MyData` available variable.

=== Injecting templates

A better way to use templates is to inject instances of `FreemarkerTemplate` in the controllers. This way, template paths are checked at build-time.

[source,java]
----
@Controller
public class SimpleEntityController {

    @Inject
    FreemarkerTemplate list; <1>
    
    @Get
    public HtmlResult list() {
        return list.render("SimpleEntities", SimpleEntity.listAll());
    }
    
}
----
<1> The path of the template will automatically set to `SimpleEntityController/list.ftlh`. It can be changed by using the `@TemplatePath` annotation.

=== Default variables

Some default variables are always added by Weblith to the Freemarker rendering context:

* `hostname`, `requestPath` and `params`: relative to the current request
* `contextPath`: value of `quarkus.http.root-path`
* `lang`: current used defined language
* `flash`: map with current Flash scope data

=== Internationalization support

`quarkus.locales` can be set to the locales supported by the application, and `quarkus.default-locale` to the default one. Then `messages.properties` files can be configure in a `i18n` directory (stored in the classpath, so in `src/main/resources`). A Weblith `LocaleHandler` will be used to detect the right language to use, but can be switched by passing a `lang` parameter to any request (can be changed via `quarkus.weblith.switchLanguageParam`).

While a `Messages` interface can be injected in any controller of internal service, two methods are also available in the templates :
 * `i18n(key,param1,param2,...)` : translates the given key
 * `prettyTime(date)` : displays date relatively

=== Other included directives