== Introduction 

=== A little bit of history

At its early stage, Weblith was an internal framework developed at https://zileo.net[Zileo.net] and derived from other frameworks like http://www.ninjaframework.org[Ninja Framework], https://github.com/svenkubiak/mangooio[MangooIO], and even https://spring.io[Spring Boot]. The focus was a on rapid (web) application development. Technically, it was based on stable well-known libraries : Google Guice, Lightbend Config, Undertow, Hibernate ORM, Hibernate Validator, Jackson, Freemarker, etc... After one year of production usage, the plan was to open source it (Q3-2020), by creating the missing documentation and archetype, and make it publicly available through http://weblith.io[a dedicated Weblith.io website].

=== Weblith goal

Weblith has been made to offer a quick and easy way to create **Server Side Rendered** web applications, focusing on fast delivery and developer joy. Opinionated decisions have been taken, allowing to minimize the developer tools needed, reduce the boiler plate code, and even offer nice reusable UI components. It uses stable and well-know libraries to avoid a long learning curve. It will produces one single Jar file with an embedded HTTP server that can run with few technical resources. Note that it doesn't reinvent the *monolithic* applications ; depending on the size of your project you should still use micro or external services when it makes sense, even with a front-end application made using Weblith.

=== Why *Quarkus powered* ?

Following the news on the Java battlefield, it was very interesting to see https://quarkus.io[Quakus] and http://micronaut.io[Micronaut] emerge. One relevant problem with Weblith was the startup time (mainly slowed by Guice and Hibernate). With the **Quarkus Global Hackathon** launched Q3-2020, there was a good opportunity to try migrating some Weblith layers to Quarkus. With some success, as the Weblith project won the Quarkus Hackathon in the _modernize an application_ category! Now it's time for making this project real and open to everyone pass:[&#127877;]