ifndef::core-tests[:core-tests: ../../../../deployment/src/test/java]

== HTTP Routes and Results

=== Resteasy integration

On a purely Quarkus point of view, Weblith works along with the `quarkus-resteasy` extension. It will automatically register JAX-RS endpoints for your web application routes, as `GET` and `POST` resources. By the way, it also means that you can mix Reasteasy code with Weblith if really needed.

=== Declaring routes

To declare new routes for your application, you only need to know three annotations : `@Controller`, `@Get` and `@Post`. Each annotation can have a value to represent the corresponding `path`, otherwise it will be taken automatically from the class name (minus the `Controller` suffix) or method name.

[source,java]
----
include::{core-tests}/test/controllers/MyFirstController.java[tag=class]
----
<1> Will produce a `/MyFirst/myPage` GET route
<2> Will produce a `/MyFirst/myPage2/{id}` GET route
<3> Will produce a `/MyFirst/myAction` POST route

NOTE: `Response` is the standard JAX-RS returned object ; you'll see later that Weblith will help you on that part too by giving you access to practical results classes.

In the previous example, Weblith uses Class, methods and parameters names as default values for building HTTP routes. But you can always be more specific by providing a string value to the corresponding annotation.

[source,java]
----
include::{core-tests}/test/controllers/MySecondController.java[tag=class]
----
<1> Will produce a `/Controller/page` GET route
<2> Will produce a `/Controller/page2/{key}` GET route
<3> Will produce a `/Controller/action` POST route

=== Route parameters

There is no specific annotation for managing parameters of your routes. As you may have noticed on the previous examples, you can use the standard JAX-RS ones : `@PathParam`, `@QueryParam`, `@HeaderParam`, `@MatrixParam`, `@CookieParam` and `@FormParam`. Be sure to import the ones from `org.jboss.resteasy.annotations.jaxrs` package so that the `name` of each one is optional (taken from the method parameter name by default). `@DefaultValue` is also available.

=== Route results

While you can configure yourself your JAR-RS `Response` objects, Weblith offers an handy way (at least for a server-side rendered web application) to manage the different results of your routes. It can be done via different types of `io.weblith.core.results.Result` objects, for example : 

* `TextResult` to render plain text
* `RawResult` to render bytes
* `StreamResult` to render a `File` or an `URL`
* `JsonResult` to render some JSON
* `HtmlResult` will be addressed in the [Freemarker Templates](=freemarker-templates) chapter
 
Result classes have some shortcut methods to configure the future response, like adding Cookies and changing the charset (`UTF-8` by default). Here are some useful examples of the predefined result classes.

[source,java]
----
include::{core-tests}/test/controllers/TextResultsController.java[tag=examples]
----

[source,java]
----
include::{core-tests}/test/controllers/StreamResultsController.java[tag=examples]
----

[source,java]
----
include::{core-tests}/test/controllers/RedirectResultsController.java[tag=examples]
----

TIP: You can also define your own custom `Result` classes if needed, by using advanced interfaces like `ConfigureResponse`, `RenderResponse` and `AutomaticCachingPolicy`.

=== GET and POST

The last one, the `Redirect` result, is an important core concept of Weblith. Weblith require the following rules:

* `GET` and `POST` methods should be distinctly used like you would do in a RESTful application.
* Successful POST actions should never directly render results.
* GET methods should never be used to modify things.
* All POST actions will be CSRF-protected (unless marked with the `@NotCsrfProtected` annotation). 

That means all the `POST` annotated methods should end up with a redirection to a `GET` annotated method. The `Redirect` result will help you this way, by allowing you to specify a human-readable result message (being a message key - check the <<i18n,Internationalization>> chapter - or the text message to display).

[source,java]
----
include::{core-tests}/test/controllers/RedirectResultsController.java[tag=with]
----
<1> Will redirect to `/` with a `You win !` success message (because such key is defined in the `messages.properties`)
<2> Will redirect to `/` with a `you.lose` warning message
<3> Will redirect to `/` with a `This is an error` error message