ifndef::core-tests[:core-tests: ../../../../deployment/src/test/java]

== Routes and Results

=== Resteasy integration

On a purely Quarkus point of view, Weblith works along with the `quarkus-resteasy` extension. It will automatically register JAX-RS endpoints for your web application routes, as `GET` and `POST` resources. By the way, it also means that you can mix Reasteasy code with Weblith if really needed.

=== Declaring routes

To declare new routes for your application, you only need to know three annotations : `@Controller`, `@Get` and `@Post`. Each annotation can have a value to represent the corresponding `path`, or it will be taken automatically from the class name (minus a `Controller` suffix) or method name.

[source,java,subs="verbatim"]
----
include::{core-tests}/test/controllers/MyFirstController.java[tag=class]
----
<1> Will produce a `/MyFirst/myPage` GET route
<2> Will produce a `/MyFirst/myPage2/{id}` GET route
<3> Will produce a `/MyFirst/myAction` POST route

NOTE: `Response` is the standard JAX-RS returned object ; you'll see later that Weblith will help you on that part too.

In the previous example, Webltith uses Class, methods and arguments names as default values. But you can always be more specific by providing a string value to the corresponding annotation.

[source,java,subs="verbatim"]
----
include::{core-tests}/test/controllers/MySecondController.java[tag=class]
----
<1> Will produce a `/Controller/page` GET route
<2> Will produce a `/Controller/page2/{key}` GET route
<3> Will produce a `/Controller/action` POST route

=== Route parameters

There is no specific annotation for managing parameters of your routes. As you may have noticed on the previous examples, you can use the standard JAX-RS ones : `@PathParam`, `@QueryParam`, `@HeaderParam`, `@MatrixParam`, `@CookieParam` and `@FormParam`. Be sure to import the ones from `org.jboss.resteasy.annotations.jaxrs` package so that the `name` of each one is optional (taken from the method parameter name by default). `@DefaultValue` is also available.

=== Route results

While you can configure yourself your JAR-RS `Response` objects, Weblith offers an handy way to manage the results of your routes via different `Result` objects : 
 * `TextResult` to render plain text
 * `RawResult` to render bytes
 * `StreamResult` to render a `File` or an `URL`
 * `JsonResult` to render some JSON
 * `HtmlResult` will be addressed in the [Freemarker Templates](=freemarker-templates) chapter
 
Result classes have some shortcut methods to configure the future response, like adding Cookies and changing the charset (`UTF-8` by default). You can also define your own custom `Result` classes if needed.

[source,java]
----
    @Get
    public Result myPage() {
        return new TextResult("Hello World").charset(StandardCharsets.UTF_8);
    }
----

One last very import one is the `Redirect` result. All your POST actions will be CSRF-protected (unless marked with @NotCsrfProtected). So GET methods should never be used to modify things ; and successful POST actions should never directly render results, but rather redirect to a GET method, with some optional information. The `Redirect` result will help you this way.

[source,java]
----
    @Post
    public Result doIt() {
        return new Redirect("/Test/myPage").withSuccess("You did it !");
    }
----