== Routes and Results

=== Resteasy integration

On a purely Quarkus point of view, Weblith works along with `quarkus-resteasy`. It will automatically register JAX-RS endpoints having to `GET` and `POST` resources. It also means that you can mix Reasteasy code with Weblith.

=== Declaring routes

To declare new routes for your application, you only need to know three annotations : `@Controller`, `@Get` and `@Post`. Each annotation can have a value to represent the corresponding `path`, or it will be taken automaticaly from the class name (minus a `Controller` suffix) or method name.

```java
@Controller
class MyFirstController {

    @Get
    public Response myPage() { ... }
    
    @Get
    public Response myPage2(@PathParam String id) { ... }
    
    @Post
    public Response myAction() { ... }
    
}
```

Will be recognized as `/MyFirst/myPage`, `/MyFirst/myPage2/{id}`,  (GET) and `/MyFirst/myAction` (POST). `Response` is the standard JAX-RS returned object ; you'll see later that Weblith will help you on that part too.

```java
@Controller("/Controller")
class MySecondController {

    @Get("/page")
    public Response myPage() { ... }
    
    @Get("/page2/{id}")
    public Response myPage2(@PathParam("id") String identifier) { ... }
    
    @Post("/action")
    public Response myAction() { ... }
    
}
```

Will be recognized as `/Controller/page`, `/Controller/page/{id}` (GET) and `/MyFirst/action` (POST).

=== Route parameters

There is no specific annotation for managing parameters of your routes. As you may have noticed on the previous examples, you can use the standard JAX-RS ones : `@PathParam`, `@QueryParam`, `@HeaderParam`, `@MatrixParam`, `@CookieParam` and `@FormParam`. Be sure to import the ones from `org.jboss.resteasy.annotations.jaxrs` package so that the `name` of each one is optional (taken from the method parameter name by default). `@DefaultValue` is also available.

=== Route results

While you can configure yourself your JAR-RS `Response` objects, Weblith offers an handy way to manage the results of your routes via different `Result` objects : 
 * `TextResult` to render plain text
 * `RawResult` to render bytes
 * `StreamResult` to render a `File` or an `URL`
 * `JsonResult` to render some JSON
 * `HtmlResult` will be addressed in the [Freemarker Templates](=freemarker-templates) chapter
 
Result classes have some shortcut methods to configure the future response, like adding Cookies and changing the charset (`UTF-8` by default). You can also define your own custom `Result` classes if needed.

```java
    @Get
    public Result myPage() {
        return new TextResult("Hello World").charset(StandardCharsets.UTF_8);
    }
```

One last very import one is the `Redirect` result. All your POST actions will be CSRF-protected (unless marked with @NotCsrfProtected). So GET methods should never be used to modify things ; and successful POST actions should never directly render results, but rather redirect to a GET method, with some optional information. The `Redirect` result will help you this way.

```java
    @Post
    public Result doIt() {
        return new Redirect("/Test/myPage").withSuccess("You did it !");
    }
```